#!/usr/bin/env bash
curl -v --silent ftp://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-latest --stderr - | grep ipv4 | grep BR | grep -v summary | awk -F "\|" '{print $4 "/" (32 - (log($5)/log(2)))}' > lista_ipv4_br.txt
curl -v --silent ftp://ftp.lacnic.net/pub/stats/lacnic/delegated-lacnic-latest --stderr - | grep ipv6 | grep BR | grep -v summary | awk -F "\|" '{print $4 "/" $5}' > lista_ipv6_br.txt
